### ISSUE TITLE
feature request: banner names in game

### ISSUE THREAD

**Issue by greener-dot-ca** [chimericdream/banner-tweaks#2]
Allow for the long distance visibility of a banner's custom name, floating above it, following the player camera akin to a player name tag.

**Comment by chimericdream** [comment]
That sounds pretty doable. Thanks for the idea!

**Comment by greener-dot-ca** [comment]
When a banner is placed on a wall, the label is 1 block too high:

![image](https://github.com/user-attachments/assets/ecb6ecd0-7721-4dcc-ac71-2a0e198af2a5)

**Comment by chimericdream** [comment]
Whoops, good catch.

**Comment by chimericdream** [comment]
Fix coming shortly
![image](https://github.com/user-attachments/assets/4c82770a-77db-43ca-b38d-01339cb1eab4)

**Comment by chimericdream** [comment]
Version 2.1.1 has just been uploaded with this feature and the fix. It should be available shortly. Thanks for the suggestion!
