### ISSUE TITLE
feature request: fix bug MC-144406

### ISSUE THREAD

**Issue by greener-dot-ca** [chimericdream/banner-tweaks#3]
on server side and client side. This would allow players to mark banners right up to the edge of maps, probably fix cases where decorations don't show up on the map and fix the player marker dropping off the map too early.

I've worked on this already https://github.com/jason-green-io/fabric-fixmapbanners

**Comment by chimericdream** [comment]
Definitely seems possible, especially with the repo you linked as a starting point.

**Comment by greener-dot-ca** [comment]
https://github.com/chimericdream/banner-tweaks/blob/5eac3411d0d80a6d8d861bd63933ee94692e31b4/src/main/java/com/chimericdream/bannertweaks/mixin/MapStateMixin.java#L74

https://github.com/chimericdream/banner-tweaks/blob/5eac3411d0d80a6d8d861bd63933ee94692e31b4/src/main/java/com/chimericdream/bannertweaks/mixin/MapStateMixin.java#L78

https://github.com/chimericdream/banner-tweaks/blob/5eac3411d0d80a6d8d861bd63933ee94692e31b4/src/main/java/com/chimericdream/bannertweaks/mixin/MapStateMixin.java#L49


My logic is a bit flawed, those `<=` need to be `<`

**Comment by greener-dot-ca** [comment]
Wait .. no .. there's more errors .. it works, but the decorations jump around on the map when you're on certain blocks. I'll figure it out.

**Comment by greener-dot-ca** [comment]
Okay

https://github.com/chimericdream/banner-tweaks/blob/5eac3411d0d80a6d8d861bd63933ee94692e31b4/src/main/java/com/chimericdream/bannertweaks/mixin/MapStateMixin.java#L45

https://github.com/chimericdream/banner-tweaks/blob/5eac3411d0d80a6d8d861bd63933ee94692e31b4/src/main/java/com/chimericdream/bannertweaks/mixin/MapStateMixin.java#L46

you can get rid of `+ 0.5`, not needed and fixes the jumping around

**Comment by chimericdream** [comment]
Version 2.1.0 is posted with this added in. Thanks for the suggestion and the help!
